services:
  - type: web
    name: pc-inventory-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn InventoryWebApp:app"
    autoDeploy: true
    envVars:
      - key: FLASK_ENV
        value: production
