services:
  - type: web
    name: pc-inventory
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Inventory Web App:Inventory Web App"
    autoDeploy: true
